### ISSUE TITLE
Ideias para o para o App

### ISSUE THREAD

**Issue by williamchitto** [yodojo/FindMeSneer#1]
1.  Ter status de disponibilidade
   • Invisível
   • Disponível
   • Disponível sob solicitação 
2.  Sistema Notificação para interagir com os contatos de forma rápida.
3.  Ordenar os contatos por proximidade
4.  Enviar a posição atual quando sair de uma localização para outra.

**Comment by dadoce** [comment]
@williamchitto tarda mas não falha.

**Comment by williamchitto** [comment]
@dadoce LOL, vamos reviver esse grupo pow

**Comment by dadoce** [comment]
@williamchitto To pronto.
